---
# tasks file for helloworld
- name: Copying application file
  copy:
    src: helloworld.js
    dest: /home/ec2-user/
    owner: ec2-user
    mode: 0644
  notify: restart helloworld

- name: copying the upstart file
  copy:
    src: helloworld.conf
    dest: /etc/init/helloworld.conf
    owner: root
    group: root
    mode: 0644
    
